# Generated by Django 2.2.16 on 2023-05-31 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_auto_20230528_2349'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Follow',
        ),
    ]
