# Generated by Django 2.2.16 on 2023-06-11 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_auto_20230609_1759'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipeingredient',
            name='unit',
        ),
        migrations.AlterField(
            model_name='recipe',
            name='cooking_time',
            field=models.PositiveIntegerField(help_text='Время приготовления (минуты)', verbose_name='Время приготовления (минуты)'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='tags',
            field=models.ManyToManyField(help_text='Выберите тэг: ', related_name='recipes', to='recipes.Tag', verbose_name='Тег'),
        ),
    ]
