# Generated by Django 2.2.16 on 2023-05-28 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20230520_2246'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfoodgram',
            name='is_subscribed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='userfoodgram',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='userfoodgram',
            name='password',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='userfoodgram',
            name='username',
            field=models.CharField(max_length=128, unique=True),
        ),
        migrations.DeleteModel(
            name='Follow',
        ),
    ]
