# Generated by Django 2.2.16 on 2023-06-09 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20230531_2330'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userfoodgram',
            name='is_subscribed',
        ),
    ]
