# Generated by Django 2.2.16 on 2023-06-15 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_userfoodgram_is_subscribed'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='follow',
            options={'ordering': ['-user'], 'verbose_name': 'Имя пользователя', 'verbose_name_plural': 'Имя пользователей'},
        ),
    ]
