# Generated by Django 2.2.16 on 2023-06-20 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20230615_2235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfoodgram',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Почта'),
        ),
        migrations.AlterField(
            model_name='userfoodgram',
            name='username',
            field=models.CharField(max_length=128, unique=True, verbose_name='Никнейм'),
        ),
    ]
